/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ty_util_SoUtil */

#ifndef _Included_com_ty_util_SoUtil
#define _Included_com_ty_util_SoUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ty_util_SoUtil
 * Method:    getAnalysis
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ty_util_SoUtil_getAnalysis
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
